server:
  port: 8080


logging:
  path: /root/logs/brand
#  path: /Users/Hero/logs/i-brand
  level.root: info

mail:
  account: "zsbyvip@163.com"
  password: "zsbyvip666"
  smtp:
    host: smtp.163.com
    port: 465
    auth: true


spring:
  cors:
    allowedOrigin: all
  datasource:
    type: "com.alibaba.druid.pool.DruidDataSource"
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF8
    url: jdbc:mysql://localhost:3306/ibrand?useUnicode=true&amp;characterEncoding=UTF8
    username: root
#    password: "root"
    password:
    driver-class-name: "com.mysql.jdbc.Driver"
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #    connectionProperties: druid.stat.mergeSql: true;
    druid.stat.slowSqlMillis: 5000

#uploadPath: /Users/Hero/
uploadPath: /root/data/img/